export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const CALCULATE_TOTALPRICE = "CALCULATE_TOTALPRICE";
export const SETPURCHASABLE = "SETPURCHASABLE";